#! /bin/sh

#pgrep -x sxhkd > /dev/null || sxhkd &

# autostart
sxhkd &
picom &
feh --bg-scale /home/machoo/pictures/wallpaper.jpg &
$home/.config/polybar/launch.sh

# Monitors
bspc monitor -d I II III IV V VI VII VIII IX X

# Basic Configuration
bspc config border_width         2
bspc config window_gap           8
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Coloring
bspc config normal_border_color 	"#797979"
bspc config focused_border_color 	"#2d64ef"

# Rules
bspc rule -a firefox desktop='^1'
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
